spring.application.name=PureVibeB
spring.datasource.url=jdbc:postgresql://localhost:5432/PureVibeB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#No envia el trace al usuario cuando hay error.
server.error.include-stacktrace=never

ip.frontend=http://54.166.157.88:4200

jwt.secret=gDbZszwxymiQDk3Q7o2V7AkoB9O1TB8XVgeQjTEuspARJQ6iI8FQadKW4ek7eI0C2NvfWUA4JhV035xZIqJDzD
